#pragma once

// From glfw3.h
#define HAZAL_MOUSE_BUTTON_1         0
#define HAZAL_MOUSE_BUTTON_2         1
#define HAZAL_MOUSE_BUTTON_3         2
#define HAZAL_MOUSE_BUTTON_4         3
#define HAZAL_MOUSE_BUTTON_5         4
#define HAZAL_MOUSE_BUTTON_6         5
#define HAZAL_MOUSE_BUTTON_7         6
#define HAZAL_MOUSE_BUTTON_8         7
#define HAZAL_MOUSE_BUTTON_LAST      HAZAL_MOUSE_BUTTON_8
#define HAZAL_MOUSE_BUTTON_LEFT      HAZAL_MOUSE_BUTTON_1
#define HAZAL_MOUSE_BUTTON_RIGHT     HAZAL_MOUSE_BUTTON_2
#define HAZAL_MOUSE_BUTTON_MIDDLE    HAZAL_MOUSE_BUTTON_3